1.Write a R program to create an array with three columns, three rows, and two "tables", taking two vectors as input to the array. Print the array.

In [1]:
vector1 <- c(5,9,3)
vector2 <- c(6,8,4)

In [2]:
array1 <- array(c(vector1,vector2),dim = c(3,3,2))
print(array1)

, , 1

     [,1] [,2] [,3]
[1,]    5    6    5
[2,]    9    8    9
[3,]    3    4    3

, , 2

     [,1] [,2] [,3]
[1,]    6    5    6
[2,]    8    9    8
[3,]    4    3    4



2.Write a R program to create a 5 × 4 matrix 

In [3]:
A = matrix(c(1:10),nrow = 5,ncol = 4,byrow = TRUE)
print(A)

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]    5    6    7    8
[3,]    9   10    1    2
[4,]    3    4    5    6
[5,]    7    8    9   10


2.1 3 × 3 matrix with labels and fill the matrix by rows

In [4]:
row_names <- c("row1", "row2","row3")
col_names <- c("col1", "col2", "col3")
B=matrix(c(1:9),nrow=3,ncol=3,byrow=TRUE,dimnames=list(row_names,col_names))
print(B)

     col1 col2 col3
row1    1    2    3
row2    4    5    6
row3    7    8    9


2.2 2 × 2 matrix with labels and fill the matrix by columns

In [5]:
row_names <- c("row1", "row2")
col_names <- c("col1", "col2")
C=matrix(c(1:4),nrow=2,ncol=2,byrow=FALSE,dimnames=list(row_names,col_names))
print(C)

     col1 col2
row1    1    3
row2    2    4


3.Imagine that you are working for the Ghostbusters, and for safety reasons you are recording the height and weight for everyone or everything the team encounters. So far you have collected information about the following. entities: Dr Peter Venkman, Dr Raymond Stantz, Dr. Eagon Spengler, Dana Barrett, Vigo, Slimer, and the Marshmallow Man.
#### Create the following two vectors: 
####  A vector called weight, storing the values: 71, 67, 83, 67
####  A vector called height, storing the values: 1.75, 1.81, 1.78, 1.82, 1.97, 2.12, 2.75 
#### You need to calculate the BMI for all you have data for. BMI is calculated by dividing the weight in kg by the height in meters squared.
####  Carry out the operation and save the result in a variable called bmi.   
####  What is your output?
#### Try printing your bmi variable.


In [6]:
weight<-c(71, 67, 83, 67)
height<-c( 1.75, 1.81, 1.78, 1.82, 1.97, 2.12, 2.75)

In [7]:
typeof(weight)

[1] "double"

In [8]:
typeof(height)

[1] "double"

In [9]:
BMI<-weight%%height
print(BMI)

Warning message in weight%%height:
"longer object length is not a multiple of shorter object length"


[1] 1.00 0.03 1.12 1.48 0.08 1.28 0.50


### Can you explain how you got the last three values, given that your weight variable only had 4 elements?

#### Ans:If we apply arithmetic operations to two vectors of unequal length, then the elements of the shorter vector
#### are recycled to complete the operations